[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "plutus_internal"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
